language: sh

sudo: required

services:
  - docker

dist: trusty

branches:
  only:
    - master

install:
  - pip3 install pyhcl

jobs:
  include:
    - env: TASK=travis-format
    - env: TASK=check-release-file
    - env: TASK=deploy
      stage: deploy

script:
  - make "$TASK"

stages:
  - test
  - name: deploy
    if: type = push
